-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.ai_inference_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  claim_id uuid,
  pre_auth_id uuid,
  model_version text NOT NULL,
  prompt_template_name text,
  input_data jsonb NOT NULL,
  output_data jsonb NOT NULL,
  confidence_score numeric,
  latency_ms integer,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  prompt_text text,
  event_type text,
  actor_id uuid,
  tenant_type text,
  tenant_id uuid,
  CONSTRAINT ai_inference_log_pkey PRIMARY KEY (id)
);
CREATE TABLE public.audit_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  actor_id uuid,
  action text NOT NULL,
  target_id uuid,
  target_type text,
  payload_hash text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  chain_seq bigint,
  prev_hash text,
  event_hash text,
  category text,
  actor_role text,
  tenant_type text,
  tenant_id uuid,
  summary text,
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT audit_log_pkey PRIMARY KEY (id)
);
CREATE TABLE public.claim_lines (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  claim_id uuid NOT NULL,
  cpt_code text NOT NULL,
  icd10_code text NOT NULL,
  units integer DEFAULT 1,
  billed_amount numeric NOT NULL DEFAULT 0,
  allowed_amount numeric DEFAULT 0,
  denial_reason text,
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT claim_lines_pkey PRIMARY KEY (id),
  CONSTRAINT claim_lines_claim_id_fkey FOREIGN KEY (claim_id) REFERENCES public.claims(id)
);
CREATE TABLE public.claims (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  claim_number text UNIQUE,
  user_id uuid,
  clinic_id uuid,
  payer_id uuid,
  member_id text,
  patient_name text,
  patient_id text,
  provider_name text,
  payer_name text,
  date_of_service date NOT NULL,
  diagnosis_codes ARRAY,
  procedure_codes ARRAY,
  total_billed numeric NOT NULL DEFAULT 0,
  total_allowed numeric DEFAULT 0,
  currency text DEFAULT 'JOD'::text,
  status text NOT NULL DEFAULT 'intake_complete'::text,
  notes text,
  scrub_result jsonb DEFAULT '{}'::jsonb,
  scrub_passed boolean DEFAULT false,
  scrub_warnings integer DEFAULT 0,
  ai_risk_score integer CHECK (ai_risk_score IS NULL OR ai_risk_score >= 0 AND ai_risk_score <= 100),
  ai_complexity_score integer CHECK (ai_complexity_score IS NULL OR ai_complexity_score >= 1 AND ai_complexity_score <= 5),
  ai_recommendation text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  routing_status text NOT NULL DEFAULT 'routed'::text CHECK (routing_status = ANY (ARRAY['routed'::text, 'unrouted'::text])),
  payer_name_raw text,
  fraud_score numeric,
  fraud_risk_level text CHECK (fraud_risk_level = ANY (ARRAY['low'::text, 'high'::text, 'extreme'::text, 'insufficient_data'::text])),
  fraud_flags jsonb DEFAULT '[]'::jsonb,
  fraud_case_id uuid,
  pre_auth_id uuid,
  pre_auth_number text,
  auth_check_status text CHECK (auth_check_status IS NULL OR (auth_check_status = ANY (ARRAY['ok'::text, 'missing'::text, 'expired'::text, 'code_mismatch'::text, 'wrong_patient'::text, 'not_applicable'::text, 'not_approved'::text, 'contradiction'::text]))),
  auth_check_detail text,
  retention_until timestamp with time zone DEFAULT (now() + '7 years'::interval),
  adjudication jsonb,
  adjudication_decision text,
  adjudicated_at timestamp with time zone,
  medical_necessity jsonb,
  fraud_signal jsonb,
  CONSTRAINT claims_pkey PRIMARY KEY (id),
  CONSTRAINT claims_pre_auth_id_fkey FOREIGN KEY (pre_auth_id) REFERENCES public.pre_auth_requests(id),
  CONSTRAINT claims_fraud_case_fk FOREIGN KEY (fraud_case_id) REFERENCES public.fraud_cases(id),
  CONSTRAINT claims_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT claims_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.provider_orgs(id),
  CONSTRAINT claims_payer_id_fkey FOREIGN KEY (payer_id) REFERENCES public.insurers(id)
);
CREATE TABLE public.claims_audit (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  claim_id uuid,
  user_id uuid,
  claim_reference_number text,
  patient_name text,
  date_of_service date,
  provider_name text,
  payer_name text,
  diagnosis_codes ARRAY,
  procedure_codes ARRAY,
  billed_amount numeric,
  ai_flags jsonb DEFAULT '[]'::jsonb,
  ai_corrections jsonb DEFAULT '{}'::jsonb,
  export_count integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT claims_audit_pkey PRIMARY KEY (id),
  CONSTRAINT claims_audit_claim_id_fkey FOREIGN KEY (claim_id) REFERENCES public.claims(id),
  CONSTRAINT claims_audit_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.doctor_join_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  doctor_id uuid NOT NULL,
  provider_org_id uuid NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text])),
  message text,
  decided_by uuid,
  decided_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT doctor_join_requests_pkey PRIMARY KEY (id),
  CONSTRAINT doctor_join_requests_doctor_id_fkey FOREIGN KEY (doctor_id) REFERENCES public.profiles(id),
  CONSTRAINT doctor_join_requests_provider_org_id_fkey FOREIGN KEY (provider_org_id) REFERENCES public.provider_orgs(id),
  CONSTRAINT doctor_join_requests_decided_by_fkey FOREIGN KEY (decided_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.doctor_org_links (
  doctor_id uuid NOT NULL,
  provider_org_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT doctor_org_links_pkey PRIMARY KEY (doctor_id, provider_org_id),
  CONSTRAINT doctor_org_links_doctor_id_fkey FOREIGN KEY (doctor_id) REFERENCES public.profiles(id),
  CONSTRAINT doctor_org_links_provider_org_id_fkey FOREIGN KEY (provider_org_id) REFERENCES public.provider_orgs(id)
);
CREATE TABLE public.erasure_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  requested_by uuid,
  requester_role text,
  tenant_type text,
  tenant_id uuid,
  subject_type text NOT NULL CHECK (subject_type = ANY (ARRAY['claim'::text, 'pre_auth'::text])),
  subject_id uuid NOT NULL,
  subject_label text,
  reason text,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'completed'::text, 'rejected'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  executed_at timestamp with time zone,
  executed_by uuid,
  CONSTRAINT erasure_requests_pkey PRIMARY KEY (id)
);
CREATE TABLE public.fraud_cases (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  claim_id uuid NOT NULL,
  insurer_id uuid,
  flag_type text,
  severity text CHECK (severity = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text, 'critical'::text])),
  confidence numeric,
  summary_en text,
  summary_ar text,
  key_evidence jsonb DEFAULT '[]'::jsonb,
  recommended_actions jsonb DEFAULT '[]'::jsonb,
  fraud_score numeric,
  anomaly_flags jsonb DEFAULT '[]'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT fraud_cases_pkey PRIMARY KEY (id),
  CONSTRAINT fraud_cases_claim_id_fkey FOREIGN KEY (claim_id) REFERENCES public.claims(id),
  CONSTRAINT fraud_cases_insurer_id_fkey FOREIGN KEY (insurer_id) REFERENCES public.insurers(id)
);
CREATE TABLE public.insurers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  name_ar text,
  country text DEFAULT 'Jordan'::text,
  cbj_operations_license text UNIQUE,
  commercial_license_number text UNIQUE,
  config jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT insurers_pkey PRIMARY KEY (id)
);
CREATE TABLE public.policy_chunks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  insurer_id uuid NOT NULL,
  content text NOT NULL,
  embedding USER-DEFINED,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT policy_chunks_pkey PRIMARY KEY (id),
  CONSTRAINT policy_chunks_insurer_id_fkey FOREIGN KEY (insurer_id) REFERENCES public.insurers(id)
);
CREATE TABLE public.pre_auth_documents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  pre_auth_id uuid NOT NULL,
  file_name text NOT NULL,
  file_type text NOT NULL,
  file_base64 text,
  extracted_text text,
  created_at timestamp with time zone DEFAULT now(),
  retention_until timestamp with time zone DEFAULT (now() + '7 years'::interval),
  CONSTRAINT pre_auth_documents_pkey PRIMARY KEY (id),
  CONSTRAINT pre_auth_documents_pre_auth_id_fkey FOREIGN KEY (pre_auth_id) REFERENCES public.pre_auth_requests(id)
);
CREATE TABLE public.pre_auth_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  insurer_id uuid,
  reference_number text NOT NULL UNIQUE,
  provider_name text NOT NULL,
  patient_name text NOT NULL,
  patient_id text NOT NULL,
  patient_age integer,
  patient_gender text,
  patient_state text,
  diagnosis_code text,
  procedure_code text,
  provider_specialty text,
  visit_type text,
  length_of_stay integer,
  insurance_type text,
  claim_amount numeric DEFAULT 0,
  currency text DEFAULT 'JOD'::text,
  status text NOT NULL DEFAULT 'processing'::text,
  sla_deadline timestamp with time zone NOT NULL,
  assigned_to uuid,
  days_between_service_and_claim integer,
  submission_month integer,
  submission_day_of_week integer,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  routing_status text NOT NULL DEFAULT 'routed'::text CHECK (routing_status = ANY (ARRAY['routed'::text, 'unrouted'::text])),
  submitted_by uuid,
  submitter_org uuid,
  payer_name_raw text,
  valid_until timestamp with time zone,
  approved_procedures jsonb DEFAULT '[]'::jsonb,
  approved_visits integer,
  approved_los_days integer,
  issued_at timestamp with time zone,
  patient_dob date,
  insurance_member_id text,
  insurance_group_number text,
  patient_phone text,
  patient_address text,
  ordering_provider_name text,
  ordering_provider_npi text,
  ordering_provider_tax_id text,
  servicing_provider_name text,
  servicing_provider_npi text,
  servicing_provider_tax_id text,
  diagnosis_codes jsonb DEFAULT '[]'::jsonb,
  procedure_codes jsonb DEFAULT '[]'::jsonb,
  modifiers text,
  ndc_code text,
  place_of_service text,
  anticipated_date_of_service date,
  priority text DEFAULT 'Standard'::text CHECK (priority IS NULL OR (priority = ANY (ARRAY['Standard'::text, 'Expedited'::text]))),
  submitted_role text CHECK (submitted_role IS NULL OR (submitted_role = ANY (ARRAY['doctor'::text, 'provider'::text]))),
  retention_until timestamp with time zone DEFAULT (now() + '7 years'::interval),
  CONSTRAINT pre_auth_requests_pkey PRIMARY KEY (id),
  CONSTRAINT pre_auth_requests_submitted_by_fkey FOREIGN KEY (submitted_by) REFERENCES public.profiles(id),
  CONSTRAINT pre_auth_requests_submitter_org_fkey FOREIGN KEY (submitter_org) REFERENCES public.provider_orgs(id),
  CONSTRAINT pre_auth_requests_insurer_id_fkey FOREIGN KEY (insurer_id) REFERENCES public.insurers(id),
  CONSTRAINT pre_auth_requests_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES public.profiles(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  account_type text NOT NULL CHECK (account_type = ANY (ARRAY['provider'::text, 'doctor'::text, 'insurance'::text, 'admin'::text])),
  full_name text,
  contact_email text,
  insurer_id uuid,
  role text,
  provider_org_id uuid,
  doctor_specialty text,
  doctor_license_number text,
  approved boolean NOT NULL DEFAULT false,
  config jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id),
  CONSTRAINT profiles_insurer_id_fkey FOREIGN KEY (insurer_id) REFERENCES public.insurers(id),
  CONSTRAINT profiles_provider_org_id_fkey FOREIGN KEY (provider_org_id) REFERENCES public.provider_orgs(id)
);
CREATE TABLE public.provider_orgs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  name_ar text,
  org_code text NOT NULL UNIQUE,
  license_number text UNIQUE,
  country text DEFAULT 'Jordan'::text,
  address text,
  contact_email text,
  config jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT provider_orgs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.waitlist_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email text NOT NULL,
  password text NOT NULL,
  account_type text NOT NULL CHECK (account_type = ANY (ARRAY['provider'::text, 'insurance'::text])),
  details jsonb NOT NULL DEFAULT '{}'::jsonb,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text])),
  reviewed_by uuid,
  reviewed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT waitlist_requests_pkey PRIMARY KEY (id),
  CONSTRAINT waitlist_requests_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES public.profiles(id)
);